#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/functions"

trigger-nginx-path-vhosts-post-proxy-ports-update() {
  declare desc="calls nginx build_config when domains are updated"
  declare trigger="post-proxy-ports-update"
  declare APP="$1" ACTION="$2"

  if [[ "$(plugn trigger proxy-type "$APP")" == "nginx-path" ]]; then
    nginx_build_config "$APP"
  fi
}

# trigger-nginx-path-vhosts-post-proxy-ports-update "$@"
echo "post-proxy-ports-update" "$@"
