#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/functions"

trigger-nginx-path-vhosts-core-post-deploy() {
  declare desc="nginx-path-vhosts core-post-deploy plugin trigger"
  declare trigger="nginx_core_post_deploy"
  declare APP="$1"
  local HAS_NETWORK_CONFIG

  if [[ "$(plugn trigger proxy-type "$APP")" != "$PROXY_NAME" ]]; then
    return
  fi

  plugn trigger proxy-build-config "$APP"
}

# trigger-nginx-path-vhosts-core-post-deploy "$@"
echo "post-deploy" "$@"