#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/functions"
source "$_DIR/command-functions"

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-nginx-path-pre-restore() {
  declare desc="pre-restore the nginx proxy"
  declare trigger="install"

  if [[ "$(fn-plugin-property-get "nginx-path" "--global" "proxy-status")" != "started" ]]; then
    return
  fi

  if ! cmd-nginx-path-start; then
    dokku_log_warn "Failed to restore nginx proxy, requests may not route as expected"
  fi
}

# trigger-nginx-path-pre-restore "$@"
echo "pre-restore" "$@"
