#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions" 


trigger-nginx-path-vhosts-proxy-disable() {
  declare desc="disable nginx proxy"
  declare trigger="proxy-disable"
  declare APP="$1"

  if [[ "$(plugn trigger proxy-type "$APP")" == "$PROXY_NAME" ]]; then
    plugn trigger domains-disable "$APP" false
    plugn trigger app-restart "$APP"
  fi
}

# trigger-nginx-path-vhosts-proxy-disable "$@"
echo "proxy-disable" "$@"
