#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/functions"

trigger-nginx-path-vhosts-scheduler-post-deploy-process() {
  declare desc="nginx-path-vhosts scheduler-post-deploy-process plugin trigger"
  declare trigger="scheduler-post-deploy-process"
  declare APP="$1" PROCESS_TYPE="$2"

  if [[ "$PROCESS_TYPE" != "web" ]]; then
    return
  fi

  if [[ "$(plugn trigger proxy-type "$APP")" != "$PROXY_NAME" ]]; then
    return
  fi

  dokku_log_info2 "Triggering early nginx proxy rebuild"
  plugn trigger proxy-build-config "$APP"
}

# trigger-nginx-path-vhosts-scheduler-post-deploy-process "$@"

echo "scheduler-post-deploy-process" "$@"
