#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/../functions"

cmd-nginx-path-vhosts-logs() {
  declare desc="display app nginx logs from command line"
  declare cmd="$1" APP="$2"

  verify_app_name "$APP"
  nginx_logs "$@"
}

cmd-nginx-path-vhosts-logs "$@"
